select * from Category
select * from Comment
select * from Post
select * from PostReaction
select * from PostTag
select * from Reaction
select * from Subscription
select * from Tag
select * from UserProfile
select * from UserType